# /etc/nginx/sites-available/descuentito
#
# Certbot va a modificar este archivo solo cuando corras el paso de HTTPS
# más abajo (agrega los listen 443 y las rutas de los certificados).
# No hace falta que edites eso a mano.

server {
    listen 80;
    server_name nico-sv.duckdns.org;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
